CREATE TABLE "todo_list_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "todo_list_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "todo_list_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "todo_list_todo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todo_list_todo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"text" varchar(280) NOT NULL,
	"isCompleted" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "todo_list_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"username" varchar(32) NOT NULL,
	"passwordHash" text NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "todo_list_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "todo_list_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "todo_list_account" ADD CONSTRAINT "todo_list_account_userId_todo_list_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."todo_list_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "todo_list_session" ADD CONSTRAINT "todo_list_session_userId_todo_list_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."todo_list_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "todo_list_todo" ADD CONSTRAINT "todo_list_todo_userId_todo_list_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."todo_list_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "todo_list_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "todo_list_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "todo_user_id_idx" ON "todo_list_todo" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "todo_created_at_idx" ON "todo_list_todo" USING btree ("createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "user_username_idx" ON "todo_list_user" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX "user_email_idx" ON "todo_list_user" USING btree ("email");